# Generated by Django 2.0.7 on 2018-07-23 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
